### ISSUE TITLE
Gamebreaking incompatibility with No Tree Punching (1.16.5) with low max stack sizes

### ISSUE THREAD

**Issue by TubaVeganMason** [PORTB/BiggerStacks#13]
From the testing I've done, when I set the max stack size to any value below 7 (I've only tested 4, 5, and 6 though due to the time consuming and laggy nature of the bug), breaking flint into flint shards against a hard object causes the game to very quickly slow down to a complete freeze as the program takes up almost 100% of my CPU and memory. The only way I can prevent the task from taking so many resources is by ending the task or pausing right before the game fully freezes and exiting the world.

This was done with only the mods No Tree Punching and Bigger Stacks enabled, both at their latest version for 1.16.5.

**Comment by TubaVeganMason** [comment]
I'm working on a realism modpack that is **painfully** realistic, so I was setting it to 4 as a healthy balance between "It's reasonable to be able to carry 8 sticks in one hand" and "It's reasonable to not be able to carry more than 1 cubic meter of gold in one hand".

**Comment by PORTB** [comment]
My initial suspicion was correct, it was integer division, but it was a mistake I made with scaling some values in a vanilla function to drop items on the ground. I hadn't considered making the stack size lower than 64. Basically, it was creating an infinite amount of drops on the ground which each contained 0 items. It should be fixed in v2.1.

Another thing I noticed is that you might run into issues if you try to blacklist items, it essentially won't do anything because the limit that container slots have will be smaller then the max stack size of that item
